# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6061010c94be79a4c113fb763eeecfb1967c8faa87757dc25d593a201e21ca224d0815cfed2aa96836e7476a11d101554965aa363f2962a0b44c9879783a9a6c

test:
  secret_key_base: 027518a8357d881b845461e7c098c17eb7244bbf382bd9e673705da3cad42700cde85e0986b328f510c9ab24f2d0c94c67ce570804f7709f5f748b6ff204bbd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
